version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app/backend/python
    # If you need to connect to a database or any other service, you can define those here too
